# .github/workflows/pushover.yaml
name: Pushover Notification

on:
  workflow_run:
    workflows: ["pkgdown.yaml"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Pushover Notification
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_API }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER_KEY }}
        with:
          title: 'GitHub Pages Deployment'
          status: ${{ github.event.workflow_run.conclusion }}
          message: |
            The 'pkgdown.yaml' workflow just finished with status: ${{ github.event.workflow_run.conclusion }}

