jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Your regular steps...

      - name: Notify success via Pushover
        if: success()
        run: |
          curl -s \
            -F "token=${{ secrets.PUSHOVER_API }}" \
            -F "user=${{ secrets.PUSHOVER_USER_KEY }}" \
            -F "message=✅ abalone: Build succeeded!" \
            https://api.pushover.net/1/messages.json

      - name: Notify failure via Pushover
        if: failure()
        run: |
          curl -s \
            -F "token=${{ secrets.PUSHOVER_API_TOKEN }}" \
            -F "user=${{ secrets.PUSHOVER_USER_KEY }}" \
            -F "message=❌ abalone: Build failed!" \
            https://api.pushover.net/1/messages.json
