# .github/workflows/pushover.yaml

# Required setting up 'secret' in Github repo settings
# Two secrets created: one called PUSHOVER_API, and other PUSHOVER_USER_KEY
# Created an application on my Pushover account which gave me the API to use

name: Pushover Notification

on:
  workflow_run:
    workflows: ["pkgdown.yaml"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Pushover Notification
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_API }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER_KEY }}
        with:
          title: 'GitHub Pages'
          status: ${{ github.event.workflow_run.conclusion }}

